language: perl

sudo: false

env:
  - AUTOMATED_TESTING=1 PREREQS="rlib Text::Diff Test::Simple Data::Printer LEONT/Module-Build-0.4224.tar.gz"

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log

install:
  # Prerequisites
  - "cpanm $PREREQS"
  - "GIT2CL='./git2cl' make ChangeLog distmeta distcheck"

test:
  - perl Build.PL && ./Build && make -f GNUMakefile

perl:
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
