language: perl

sudo: false

env:
  - AUTOMATED_TESTING=1 PREREQS="rlib Text::Diff Test::Simple"

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log

install:
  # Prerequisites
  - "cpanm $PREREQS"
  - "make ChangeLog distmeta distcheck"

perl:
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
